// Core types for camping app

export type CampingStyle =
  | "CAR_CAMPING"
  | "BACKPACKING"
  | "RV"
  | "HAMMOCK"
  | "ROOFTOP_TENT"
  | "OVERLANDING"
  | "BOAT_CANOE"
  | "BIKEPACKING"
  | "WINTER"
  | "DISPERSED";

export type CampingStyleValue = "CAR_CAMPING" | "BACKPACKING" | "RV" | "HAMMOCK" | "ROOFTOP_TENT" | "OVERLANDING" | "BOAT_CANOE" | "BIKEPACKING" | "WINTER" | "DISPERSED";

export type TripStatus = "planning" | "upcoming" | "active" | "completed" | "cancelled";

export type ParkType =
  | "national_park"
  | "state_park"
  | "national_forest"
  | "blm_land"
  | "private";

export interface Coordinates {
  latitude: number;
  longitude: number;
}

export interface Destination {
  id: string;
  name: string;
  coordinates?: Coordinates;
  address?: string;
  city?: string;
  state?: string;
}

export interface Trip {
  id: string;
  name: string;
  startDate: string; // ISO string
  endDate: string; // ISO string
  destination?: Destination;
  campingStyle?: CampingStyle;
  partySize?: number;
  notes?: string;
  description?: string;
  status?: TripStatus;
  createdBy?: string;
  userId: string; // User ID for Firebase scoping (required)
  parkId?: string; // Reference to selected park
  locationName?: string; // Custom location name
  locationType?: "park" | "custom";
  coordinates?: Coordinates;
  createdAt: string;
  updatedAt: string;
  parks?: string[];
  customCampgrounds?: any[];
  packing?: {
    categories: GearCategory[];
    itemsChecked: number;
    totalItems: number;
  };
  meals?: any[];
  weather?: {
    forecast: WeatherForecast[];
    lastUpdated: string;
  };
}

export interface Park {
  id: string;
  name: string;
  filter: "national_park" | "state_park" | "national_forest";
  address: string;
  state: string;
  latitude: number;
  longitude: number;
  url: string;
}

export interface GearCategory {
  id: string;
  name: string;
  items: GearItem[];
}

export interface GearItem {
  id: string;
  name: string;
  packed: boolean;
  quantity?: number;
  notes?: string;
}

export interface PackingList {
  id: string;
  tripId?: string;
  name: string;
  categories: GearCategory[];
  createdAt: string;
  updatedAt: string;
}

export interface WeatherForecast {
  date: string;
  high: number;
  low: number;
  condition: string;
  icon: string;
  precipitation?: number;
}

// Packing list item for Firebase
export interface PackingItem {
  id: string;
  category: string;
  label: string;
  quantity: number;
  isPacked: boolean;
  isAutoGenerated: boolean;
  notes?: string;
}

// Meal for Firebase
export interface Meal {
  id: string;
  name: string;
  category: "breakfast" | "lunch" | "dinner" | "snack";
  dayIndex: number; // 1-based day of trip
  sourceType: "library" | "custom";
  libraryId?: string;
  prepType: "cold" | "campStove" | "campfire" | "noCook";
  ingredients?: string[];
  instructions?: string;
  notes?: string;
}

// Meal library item (global shared meals)
export interface MealLibraryItem {
  id: string;
  name: string;
  category: "breakfast" | "lunch" | "dinner" | "snack";
  prepType: "cold" | "campStove" | "campfire" | "noCook";
  difficulty: "easy" | "moderate";
  suitableFor?: CampingStyle[];
  ingredients: string[];
  instructions: string;
  tags?: string[];
}

// Camp template (for auto-generating packing lists and meal suggestions)
export interface CampTemplate {
  id: string;
  campStyle: CampingStyle;
  name: string;
  baseItems: Omit<PackingItem, "id" | "isPacked">[];
  seasonalModifiers?: {
    cold?: Omit<PackingItem, "id" | "isPacked">[];
    rainy?: Omit<PackingItem, "id" | "isPacked">[];
    hot?: Omit<PackingItem, "id" | "isPacked">[];
  };
}
